/*
 * This file is generated by jOOQ.
 */
package com.testTask.db;


import com.testTask.db.tables.User;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USER_LOGIN_KEY = Indexes0.USER_LOGIN_KEY;
    public static final Index USER_NICK_KEY = Indexes0.USER_NICK_KEY;
    public static final Index USER_PKEY = Indexes0.USER_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index USER_LOGIN_KEY = Internal.createIndex("user_login_key", User.USER, new OrderField[] { User.USER.LOGIN }, true);
        public static Index USER_NICK_KEY = Internal.createIndex("user_nick_key", User.USER, new OrderField[] { User.USER.NICK }, true);
        public static Index USER_PKEY = Internal.createIndex("user_pkey", User.USER, new OrderField[] { User.USER.ID }, true);
    }
}
